name: Build Binaries

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

# Add permissions for the GITHUB_TOKEN
permissions:
  contents: write  # This is required for creating releases and uploading assets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Initialize Go module and install dependencies
        run: |
          go mod tidy
          go get github.com/google/uuid

      - name: List repository contents
        run: |
          echo "Repository contents:"
          ls -la
          echo "Go files:"
          find . -name "*.go" -type f

      - name: List repository contents
        run: |
          echo "Repository contents:"
          ls -la
          echo "Go files:"
          find . -name "*.go" -type f

      - name: Build Windows binary
        run: |
          # Build with the files that actually exist
          GOOS=windows GOARCH=amd64 go build -o leo_venice_config.exe
          zip -r leo_venice_config.exe.zip leo_venice_config.exe

      - name: Build macOS binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o leo_venice_config_mac
          chmod +x leo_venice_config_mac
          zip -r leo_venice_config_mac.zip leo_venice_config_mac

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o leo_venice_config_linux
          chmod +x leo_venice_config_linux
          zip -r leo_venice_config_linux.zip leo_venice_config_linux

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: leo_venice_config_windows
          path: leo_venice_config.exe.zip

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: leo_venice_config_mac
          path: leo_venice_config_mac.zip

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: leo_venice_config_linux
          path: leo_venice_config_linux.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ./leo_venice_config_windows/leo_venice_config.exe.zip
            ./leo_venice_config_mac/leo_venice_config_mac.zip
            ./leo_venice_config_linux/leo_venice_config_linux.zip